### ISSUE TITLE
Need HI-TECH PIC C Compiler for Linux

### ISSUE THREAD

**Issue by chayanforyou** [Manouchehri/Microchip-C18-Lite#2]
Hi Manouchehri,
Can you provide hitech pic compiler for Linux?

Thanks

**Comment by Manouchehri** [comment]
It's been close to a decade since I last worked with Microchip stuff. Any reason you need the HI-TECH compiler instead of C18 (IIRC the reason I used C18, was because I was using old libraries written for HI-TECH)?

You can try looking here too: https://www.microchip.com/en-us/tools-resources/archives/mplab-ecosystem#

**Comment by chayanforyou** [comment]
I need HI-TECH because my project is complied with this compiler in my windows machine. Now I want to work in my project using my Linux machine.

**Comment by chayanforyou** [comment]
Finally I got it
https://github.com/chayanforyou/HI-TECH-PIC-C-Compiler-Linux
